# This workflow will install Python dependencies and submit a Dynamic Scan.
# Be sure to setup your secrets for VERACODE_API_ID and VERACODE_API_KEY.


name: Submit a Veracode Dynamic scan using Python

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  SubmitDynamicScan:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Submit the DAST scan
      run: |
        export VERACODE_API_KEY_ID="${{secrets.VERACODE_API_ID}}"
        export VERACODE_API_KEY_SECRET="${{secrets.VERACODE_API_KEY}}"
        python vc-dast.py
